services:
  ## User service
  mongo-user:
    image: mongo:noble
    command: [ 'mongod', '--quiet', '--logpath', '/dev/null' ]
    ports:
      - '27017:27017'
    volumes:
      - mongo_data_user:/codemaster/user/db
    networks:
      - codemaster-net

  mongo-express-user:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    ports:
      - '8081:8081'
    depends_on:
      mongo-user:
        condition: service_started
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://mongo-user:27017/codemaster-user-db"
      ME_CONFIG_BASICAUTH_USERNAME: "admin"
      ME_CONFIG_BASICAUTH_PASSWORD: "admin"
    networks:
      - codemaster-net

  ## Authentication service
  mongo-authentication:
    image: mongo:noble
    command: [ 'mongod', '--quiet', '--logpath', '/dev/null' ]
    ports:
      - '27018:27017'
    volumes:
      - mongo_data_authentication:/codemaster/authentication/db
    networks:
      - codemaster-net

  mongo-express-authentication:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    ports:
      - '8082:8081'
    depends_on:
      mongo-authentication:
        condition: service_started
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://mongo-authentication:27017/codemaster-authentication-db"
      ME_CONFIG_BASICAUTH_USERNAME: "admin"
      ME_CONFIG_BASICAUTH_PASSWORD: "admin"
    networks:
      - codemaster-net

  ## Codequest service
  mongo-codequest:
    image: mongo:noble
    command: [ 'mongod', '--quiet', '--logpath', '/dev/null' ]
    ports:
      - '27019:27017'
    volumes:
      - mongo_data_codequest:/codemaster/codequest/db
    networks:
      - codemaster-net

  mongo-express-codequest:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    ports:
      - '8083:8081'
    depends_on:
      mongo-codequest:
        condition: service_started
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://mongo-codequest:27017/codemaster-codequest-db"
      ME_CONFIG_BASICAUTH_USERNAME: "admin"
      ME_CONFIG_BASICAUTH_PASSWORD: "admin"
    networks:
      - codemaster-net

  ## Community service
  mongo-community:
    image: mongo:noble
    command: [ 'mongod', '--quiet', '--logpath', '/dev/null' ]
    ports:
      - '27021:27017'
    volumes:
      - mongo_data_community:/codemaster/community/db
    networks:
      - codemaster-net

  mongo-express-community:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    ports:
      - '8085:8081'
    depends_on:
      mongo-community:
        condition: service_started
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://mongo-community:27017/codemaster-community-db"
      ME_CONFIG_BASICAUTH_USERNAME: "admin"
      ME_CONFIG_BASICAUTH_PASSWORD: "admin"
    networks:
      - codemaster-net

  ## Solution service
  mongo-solution:
    image: mongo:noble
    command: [ 'mongod', '--quiet', '--logpath', '/dev/null' ]
    ports:
      - '27020:27017'
    volumes:
      - mongo_data_solution:/codemaster/solution/db
    networks:
      - codemaster-net

  mongo-express-solution:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    ports:
      - '8084:8081'
    depends_on:
      mongo-solution:
        condition: service_started
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://mongo-solution:27017/codemaster-solution-db"
      ME_CONFIG_BASICAUTH_USERNAME: "admin"
      ME_CONFIG_BASICAUTH_PASSWORD: "admin"
    networks:
      - codemaster-net

  ## Generator service
  mongo-generator:
    image: mongo:noble
    command: [ 'mongod', '--quiet', '--logpath', '/dev/null' ]
    ports:
      - '27022:27017'
    volumes:
      - mongo_data_generator:/codemaster/generator/db
    networks:
      - codemaster-net

  mongo-express-generator:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    ports:
      - '8086:8081'
    depends_on:
      mongo-generator:
        condition: service_started
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://mongo-generator:27017/codemaster-generator-db"
      ME_CONFIG_BASICAUTH_USERNAME: "admin"
      ME_CONFIG_BASICAUTH_PASSWORD: "admin"
    networks:
      - codemaster-net

volumes:
  mongo_data_user:
  mongo_data_authentication:
  mongo_data_codequest:
  mongo_data_solution:
  mongo_data_community:
  mongo_data_generator:
