/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.12/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "CodeMaster"

plugins {
    id("org.danilopianini.gradle-pre-commit-git-hooks") version "2.1.5"
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

gitHooks {
    commitMsg { conventionalCommits() }
    preCommit { tasks("npmTest", "test") }
    createHooks(true)
}

include("codequest-service")
include("authentication-service")
include("user-service")
include("solution-service")
include("community-service")
include("code-generator-service")
include("frontend-service")