services:
  mongo:
    image: mongo
    command: ['mongod', '--quiet', '--logpath', '/dev/null']
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/codemaster/user/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo

  codemaster-user-service:
    image: codemaster-user-service
    restart: always
    ports:
      - '8080:4005'
    depends_on:
      - mongo
    env_file:
      - ./.env

volumes:
  mongo_data:
