spring.application.name=generatorservice
spring.mongodb.uri=${MONGO_URI}
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
server.port=${PORT}