services:

  mongo:
    image: mongo
    command: mongod --quiet --logpath /dev/null 
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH: false

  # rabbitmq:
  #   image: rabbitmq:3.10-rc-management-alpine
  #   ports:
  #     # AMQP protocol port
  #     - "5672:5672"
  #     # HTTP management UI
  #     - "15672:15672"

  codequest-services:
    image: codequest-service
    restart: always
    ports:
      - 8080:3000
    links:
      - mongo-express
    depends_on:
      - mongo-express